export const FALLBACK_PACKAGES = [
    {
        id: 'PKG-001',
        code: 'PKG-001',
        name: 'Gói Miễn Phí',
        price: 0,
        durationUnit: 'permanent',
        durationValue: null,
        benefits: ['1 CV', 'AI cơ bản'],
        totalUsers: 15420,
        status: 'ACTIVE',
        createdAt: '2026-04-10T08:30:00.000Z',
        description: 'Gói miễn phí cho người dùng mới.',
        maxCv: 1,
        aiLimit: 10,
        premiumCv: false,
        removeWatermark: false,
        customDomain: false,
        support247: false,
        allowAiAddon: false,
        fullAiAnalysis: false,
    },
    {
        id: 'PKG-002',
        code: 'PKG-002',
        name: 'Gói Premium',
        price: 199000,
        durationUnit: 'year',
        durationValue: 1,
        benefits: [
            '50 CV',
            'AI 100 lượt',
            'Dùng template premium',
            'Xuất CV không watermark',
            'Hỗ trợ 24/7',
        ],
        totalUsers: 1284,
        status: 'ACTIVE',
        createdAt: '2026-04-09T08:30:00.000Z',
        description:
            'Gói tối ưu dành cho ứng viên chuyên nghiệp muốn nổi bật giữa đám đông với sức mạnh từ AI.',
        maxCv: 50,
        aiLimit: 100,
        premiumCv: true,
        removeWatermark: true,
        customDomain: true,
        support247: true,
        allowAiAddon: false,
        fullAiAnalysis: false,
    },
    {
        id: 'PKG-003',
        code: 'PKG-003',
        name: 'Doanh Nghiệp',
        price: 4990000,
        durationUnit: 'year',
        durationValue: 1,
        benefits: ['Hỗ trợ 24/7', 'White Label'],
        totalUsers: 142,
        status: 'PAUSED',
        createdAt: '2026-04-08T08:30:00.000Z',
        description: 'Gói doanh nghiệp với quản trị nâng cao.',
        maxCv: 200,
        aiLimit: 500,
        premiumCv: true,
        removeWatermark: true,
        customDomain: true,
        support247: true,
        allowAiAddon: true,
        fullAiAnalysis: true,
    },
];

export const DEFAULT_FORM_DATA = {
    id: '',
    code: '',
    name: '',
    price: '',
    durationUnit: 'year',
    durationValue: '1',
    description: '',
    maxCv: '50',
    aiLimit: '100',
    premiumCv: true,
    removeWatermark: true,
    customDomain: true,
    support247: true,
    allowAiAddon: false,
    fullAiAnalysis: false,
    totalUsers: 0,
    status: 'ACTIVE',
};