export const router = {
    // Public
    home: '/',
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    otp_verify: '/otp/verify',
    reset_pass: '/otp/reset',
    verify_success: '/verify/success',
    forgot_password: '/forgot-password',
    cvSample: '/cv-templates',
    CvDetail: '/cv-templates/:templateId',
    pricing: '/pricing',
    // createCV: '/create-cv',
    // User
    dashboard: '/dashboard',
    cvTemplates: '/user/cv-templates',
    CvTemplateDetail: '/cv-templates/:templateId',
    // cvEditorRouter: '/cv-editor',
    cvEditor: '/cv-editor/:cvId',
    myCvs: '/my-cvs',
    aiAnalysis: '/ai-analysis',
    upgradePremium: '/upgrade-premium',
    profile: '/profile',
    security: '/security',
    package: '/package',
    history: '/history',
    // Admin
    adminDashboard: '/admin/dashboard',
    manageUsers: '/admin/manage-users',
    manageTemplates: '/admin/templates',
    adminSettings: '/admin/settings',
    manageOrders: '/admin/orders',
    managePackages: '/admin/packages',
};
